package proyecto.umg.vistas;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import model.ChkRolesPorUsuario;
import model.ChkUsuario;
import proyecto.umg.admin.UsuarioList;
import proyecto.umg.base.ViewBase;
import proyecto.umg.componentes.MenuItemUQ;
import proyecto.umg.crud.BancoList;
import proyecto.umg.crud.ChequeraList;
import proyecto.umg.crud.CuentaList;
import proyecto.umg.crud.ProveedorList;
import proyecto.umg.login.Login;

import com.google.gwt.dom.client.Style.FontWeight;
import com.google.gwt.user.client.ui.HorizontalSplitPanel;
import com.sun.corba.se.impl.encoding.CodeSetConversion.BTCConverter;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.Page;
import com.vaadin.server.Resource;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class Menu extends ViewBase implements View, Command {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public void enter(ViewChangeEvent event) {
		if (verificaSesion()){
			construirMenuPorRoles();
		}
		

	}
	
	private VerticalLayout layout;
	private GridLayout layoutPrincipal;
	private TabSheet tabs;
	private MenuBar barmenu;
	private Label selection;
	
	
	
	public Menu(){
		System.out.println("Aqui estoy ya en la sesion ");		
		selection = new Label("-");
		selection.setStyleName("textolabel");
		buildMainLayout();
		setSizeFull();
		setCompositionRoot(layoutPrincipal);
		setStyleName("desktop-app");
	}
	
	@AutoGenerated
	private void buildMainLayout() {
		layout = new VerticalLayout();
		layoutPrincipal = new GridLayout(1,3);
		layoutPrincipal.setSizeFull();
		layoutPrincipal.setRowExpandRatio(1, 1);
		layout.addComponent(new Label("CONTENIDO"));
		layout.setStyleName("content-style");
		
		
		//layout.setMargin(true);				
	}
	
	private void construirMenuPorRoles(){
		 // Put some items in the menu hierarchically
		ChkUsuario user = (ChkUsuario) obtieneVariableSesion("USUARIO");
		Map<String, String> permisos = (Map<String, String>) obtieneVariableSesion("PERMISOS");
		if (permisos == null){
			permisos = new HashMap<String, String>();
			
			if (user != null){
				for (ChkRolesPorUsuario rolact: user.getChkRolesPorUsuarios()){
					String r = rolact.getChkRol().getRol();
					if (rolact.getEstado().intValue() == 1){
						permisos.put(r, "S");
					}
										
				}
			}
		}
		if (barmenu == null){
			barmenu = new MenuBar();
			
			
		}
		layoutPrincipal.addComponent(layout,0,1);
		layoutPrincipal.setComponentAlignment(layout, Alignment.MIDDLE_CENTER);
		layout.setWidth("100%");
		layout.setHeight("100%");
		Layout header = new HorizontalLayout(barmenu);
		header.setStyleName("barmenu");
		header.setWidth("100%");
		barmenu.removeItems();
		
		
		layoutPrincipal.addComponent(header,0,0);
		
		
		Label lblFoot = new Label("Usuario Ingresado:  "+user.getUsername());
		
		lblFoot.setStyleName("textolabel");
		
		Layout footer = new HorizontalLayout(lblFoot);
		footer.setWidth("100%");
		footer.setStyleName("barmenu");
		layoutPrincipal.addComponent(footer);

		//layout.addComponent(barmenu);
		barmenu.addItem("Home", FontAwesome.HOME,this);
		
		if (permisos.get("CONTABILIDAD")!= null ){
			MenuBar.MenuItem conta1 = barmenu.addItem("Catalogos", FontAwesome.BANK,null);
			conta1.addItem("Bancos", FontAwesome.BARCODE,this);
			conta1.addItem("Proveedores", FontAwesome.BARCODE,this);
			conta1.addItem("Chequeras", FontAwesome.BARCODE,this);
			conta1.addItem("Cuentas Bancarias", FontAwesome.BARCODE,this);
			MenuBar.MenuItem conta2 = barmenu.addItem("Cuentas Bancarias", FontAwesome.BANK,null);
			conta2.addItem("Registrar Depositos a Cuenta", FontAwesome.BANK, this);
			conta2.addItem("Reporte de Movimientos de Cuenta", FontAwesome.ANDROID, this);			
		}
		
		if (permisos.get("PAGOS")!= null | permisos.get("AUDITORIA") != null | permisos.get("GERENCIA") != null | permisos.get("JEFE_PAGOS")!= null){
			MenuBar.MenuItem pagos = barmenu.addItem("Pagos", FontAwesome.BANK,null);
			if (permisos.get("JEFE_PAGOS")!= null){
				pagos.addItem("Modificar Cheques", FontAwesome.BARCODE,this);
			}
			if (permisos.get("PAGOS")!= null){
				pagos.addItem("Generacion de Cheques", FontAwesome.BARCODE,this);
			}
			pagos.addItem("Generacion de Cheques", FontAwesome.BARCODE,this);
			if (permisos.get("AUDITORIA") != null | permisos.get("GERENCIA") != null | permisos.get("CONSEJO") != null){
				pagos.addItem("Liberacion de Cheques", FontAwesome.ARCHIVE, this);
			}
			if (permisos.get("CONSEJO") != null){
				pagos.addItem("Configuracion", FontAwesome.ARCHIVE, this);
			}
			
		}
		
		if (permisos.get("ADMINISTRADOR") != null | permisos.get("CONSEJO") != null){			
			MenuBar.MenuItem administracion = barmenu.addItem("Administracion", FontAwesome.ADJUST,null);
			MenuBar.MenuItem adminCat = administracion.addItem("Gestion de Usuarios y Roles", FontAwesome.ADN, null);
			adminCat.addItem("Catalogo de Usuarios", FontAwesome.USERS, this);
//			adminCat.addItem("Roles", FontAwesome.USERS, this);
//			adminCat.addItem("Asignacion de Roles", FontAwesome.USER_MD,this);		
			if (permisos.get("CONSEJO") != null){
				adminCat.addItem("Configuracion", FontAwesome.ARCHIVE, this);
			}
			
		}	
		barmenu.addItem("Salir", FontAwesome.USERS,this);
	}

	@Override
	public void menuSelected(MenuItem selectedItem) {
		System.out.println("Item seleccionado  "+selectedItem.getText());
		String seleccion = selectedItem.getText();
		if (seleccion.equals("Home")){
			addComponentCenter(new CustomComponent());			
		}
		if (seleccion.equals("Salir")){
			cerrarSesion(Page.getCurrent());
		}	
		if (seleccion.equals("Catalogo de Usuarios")){
			addComponentCenter(new UsuarioList());
		}
		if (seleccion.equals("Bancos")){
			addComponentCenter(new BancoList());
		}
		if (seleccion.equals("Cuentas Bancarias")){
			addComponentCenter(new CuentaList());
		}
		if (seleccion.equals("Chequeras")){
			addComponentCenter(new ChequeraList());
		}
		if (seleccion.equals("Proveedores")){
			addComponentCenter(new ProveedorList());
		}
		
	}
	
	private void addComponentCenter(CustomComponent comp){
		layoutPrincipal.removeAllComponents();
		construirMenuPorRoles();
		layoutPrincipal.removeComponent(layout);
		layoutPrincipal.addComponent(comp,0,1);
		
		layoutPrincipal.setComponentAlignment(comp, Alignment.TOP_CENTER);
	}
	

}
