package proyecto.umg.vistas;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import model.ChkRolesPorUsuario;
import model.ChkUsuario;
import proyecto.umg.admin.UsuarioList;
import proyecto.umg.base.ViewBase;
import proyecto.umg.componentes.MenuItemUQ;
import proyecto.umg.login.Login;

import com.google.gwt.user.client.ui.HorizontalSplitPanel;
import com.sun.corba.se.impl.encoding.CodeSetConversion.BTCConverter;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.Resource;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class Menu extends ViewBase implements View, Command {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public void enter(ViewChangeEvent event) {
		if (verificaSesion()){
			construirMenuPorRoles();
		}
		

	}
	
	private VerticalLayout layout;
	private GridLayout layoutPrincipal;
	private TabSheet tabs;
	private MenuBar barmenu;
	private Label selection;
	
	
	
	public Menu(){
		System.out.println("Aqui estoy ya en la sesion ");		
		selection = new Label("-");
		selection.setStyleName("textolabel");
		buildMainLayout();
		setSizeFull();
		setCompositionRoot(layoutPrincipal);
		setStyleName("desktop-app");
	}
	
	@AutoGenerated
	private void buildMainLayout() {
		layout = new VerticalLayout();
		layoutPrincipal = new GridLayout(1,3);
		layoutPrincipal.setSizeFull();
		layoutPrincipal.setRowExpandRatio(1, 1);
		layout.setWidth("100%");
		layout.setHeight("100%");
		//layout.setMargin(true);				
	}
	
	private void construirMenuPorRoles(){
		 // Put some items in the menu hierarchically
		ChkUsuario user = (ChkUsuario) obtieneVariableSesion("USUARIO");
		Map<String, String> permisos = (Map<String, String>) obtieneVariableSesion("PERMISOS");
		if (permisos == null){
			permisos = new HashMap<String, String>();
			
			if (user != null){
				for (ChkRolesPorUsuario rolact: user.getChkRolesPorUsuarios()){
					String r = rolact.getChkRol().getRol();
					if (rolact.getEstado().intValue() == 1){
						permisos.put(r, "S");
					}
										
				}
			}
		}
		if (barmenu == null){
			barmenu = new MenuBar();
			
			
		}
		Layout header = new HorizontalLayout(barmenu);
		header.setStyleName("barmenu");
		header.setWidth("100%");
		barmenu.removeItems();
		
		
		layoutPrincipal.addComponent(header,0,0);
		
		layout.addComponent(new Label("CONTENIDO"));
		layout.setStyleName("content-style");
		
		layoutPrincipal.addComponent(layout,0,1);
		Label lblFoot = new Label("Usuario Ingresado:  "+user.getUsername());
		
		lblFoot.setStyleName("textolabel");
		
		Layout footer = new HorizontalLayout(lblFoot);
		footer.setWidth("100%");
		footer.setStyleName("barmenu");
		layoutPrincipal.addComponent(footer);
		layoutPrincipal.setComponentAlignment(layout, Alignment.MIDDLE_CENTER);
		//layout.addComponent(barmenu);
		
		if (permisos.get("PAGOS")!= null){
			MenuBar.MenuItem pagos = barmenu.addItem("Pagos", FontAwesome.BANK,null);
			pagos.addItem("Generacion de Cheques", FontAwesome.BARCODE,this);
			
		}
		
		if (permisos.get("ADMINISTRADOR") != null){
			//barmenu.addItemBefore(caption, icon, command, itemToAddBefore);
			//MenuItemUQ administracion = new MenuItemUQ(barmenu,"Settings", FontAwesome.ADJUST,this,1);
			//barmenu.addItemBefore("Settings", FontAwesome.ADJUST, this, administracion);
			MenuBar.MenuItem administracion = barmenu.addItem("Settings", FontAwesome.ADJUST,null);
			administracion.addItem("Gestion de Usuarios", FontAwesome.APPLE,this);			
			
			
		}
		
		barmenu.addItem("Salir", FontAwesome.USERS,this);
		
		
		
		
//		
//        MenuBar.MenuItem beverages =
//            barmenu.addItem("Bebidas", null, null);
//        MenuBar.MenuItem hot_beverages =
//            beverages.addItem("Calientes", null, null);
//        hot_beverages.addItem("Te", null, this);
//        hot_beverages.addItem("Cafe", null, this);
//        beverages.setVisible(validaRol("ADMINISTRADOR"));
//        MenuBar.MenuItem cold_beverages =
//            beverages.addItem("Frías", null, null);
//        cold_beverages.addItem("Leche", null, this);
//        cold_beverages.addItem("Chela", null, this);
//        
//        // Another top-level item
//        MenuBar.MenuItem snacks =
//            barmenu.addItem("Boquitas", null, null);
//        snacks.addItem("Manías", null, this);
//        snacks.addItem("Mango con Limon", null, this);
//        snacks.addItem("Granizada", null, this);
//        snacks.setVisible(validaRol("GATO"));
//        
//        // Yet another top-level item
//        MenuBar.MenuItem services =
//            barmenu.addItem("Servicios", null, null);
//        services.addItem("Servicio de Pedos", null, this);        
        // END-EXAMPLE: component.menubar.basic
		
//		tabs = new TabSheet();
//		tabs.setSizeFull();
//		//PANTALLAS DE LA APLICACION
//		
//		tabs.addTab(new Inicio(),"Pagina Inicio");
//		tabs.addTab(new Login(),"Login");
//		layout.addComponent(tabs);
//		layout.setComponentAlignment(tabs, Alignment.MIDDLE_CENTER);
		
//		mainLayout = new AbsoluteLayout();
//		layout = new VerticalLayout();
//		layout.setWidth("100%");
//		layout.setHeight("100%");
//		layout.setMargin(true);
//		FormLayout form = new FormLayout();
//		
//		//
//		Label lblUser = new Label("Usuario");
//		lblUser.setStyleName("textolabel");
//		
//		txtUsuario.addValidator(new StringLengthValidator(
//			    "El usuario solo puede tener de 1 a 10 letras (was {0})",
//			    1, 10, true));
//		txtUsuario.setImmediate(true);
//		txtUsuario.setValidationVisible(true);
//		txtUsuario.setRequired(true);
//		Label lblPass = new Label("Contraseña");
//		lblPass.setStyleName("textolabel");
//		form.setWidth("400px");
//		form.setHeight("400px");
////		form.setWidth(60, Unit.PERCENTAGE);
////		form.setHeight(30, Unit.PERCENTAGE);
//		form.addComponent(lblUser);		
//		form.addComponent(txtUsuario);
//		form.addComponent(lblPass);
//		form.addComponent(txtPass);
//		txtPass.setValidationVisible(true);
//		txtPass.setRequired(true);
////		form.addComponent(select);
//		Button boton = new Button("Iniciar Sesion");
//		boton.addClickListener(this);
//		form.addComponent(boton);
//		layout.addComponent(form);		
//		layout.setComponentAlignment(form, Alignment.MIDDLE_CENTER);
	}

	@Override
	public void menuSelected(MenuItem selectedItem) {
		System.out.println("Item seleccionado  "+selectedItem.getText());
		String seleccion = selectedItem.getText();
		if (seleccion.equals("Salir")){
			VaadinSession.getCurrent().getSession().invalidate();
			navegar("");
			info("Sesion terminada", "<b>Terminada la sesion  </b>"+new Date(), null,"ok.png");
		}
		if (seleccion.equals("Gestion de Usuarios")){
//			layout.removeAllComponents();
//			layout.addComponent(new UsuarioList());
			layoutPrincipal.removeComponent(layout);
			layoutPrincipal.addComponent(new UsuarioList(), 0,1);
		}
		
	}
	
	

}
